version: '3.8'

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
      - WORKERS=1
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: ["python", "main.py", "--dev"]
    ports:
      - "8000:8000"
      - "8001:8001"  # Additional port for debugging